id = "zsh"
name = "Zsh"
version = "0.0.1"
schema_version = 1
authors = ["Amaan Bilwar <amaan@soarailabs.com>"]
description = "Zsh shell language support for Zed."
repository = "https://github.com/AmaanBilwar/zsh-zed"

[grammars.zsh]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-zsh"
rev = "47e2caf4ed7e466f51cfbb13a860a192c300506f"
